### PR TITLE
calendar for canteen lunches

### PR DESCRIPTION
**Pull request by mgrfilipmarek**
This is the first (prototype) of edupage canteen calendar with lunches loaded if available. We can add and adjust loaded data in the next steps or after some feedback. For example allergens, rating or weight.

### CODE REVIEW

**Comment by rine77** [comment]
Thanks!

some points:
* we should make canteen menu optional, so e.g. if there is no module in school edupage instance, than there is no entity for it. Do you think it's possible?
* when I test this branch I dont have any grade sensors anymore and student_name is None in notifications sensor (it crashes unidecode) and also calendar is no more functional. Even if remove integration and reinstall.
*  I sonst have lots of spare time atm due to real life work but I see you are getting deeper into the rabbit hole day by day :) thanks man

**Comment by rine77** [comment]
* "failed to fetch timetable:" word "timetable" is to be removed cause the try/catch block handled all data. Maybe we should try/except all steps alone, but in this case its because of the missing data of get_lunched():
 
2024-12-17 13:42:30.120 ERROR (MainThread) [custom_components.homeassistant_edupage] INIT Failed to fetch timetable: EDUPAGE error updating get_lunches() data for 2024-12-17: list index out of range

* next error is because unicode tries to access a None object:

2024-12-17 14:22:45.286 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up homeassistantedupage platform for sensor
Traceback (most recent call last):
  File "/home/rine/Projekte/homeassistantedupage/.venv/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/home/rine/Projekte/homeassistantedupage/custom_components/homeassistantedupage/sensor.py", line 45, in async_setup_entry
    notify = EduPageNotificationSensor(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rine/Projekte/homeassistantedupage/custom_components/homeassistantedupage/sensor.py", line 121, in __init__
    self._student_name = unidecode(student_name).replace(' ', '_').lower()
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rine/Projekte/homeassistantedupage/.venv/lib/python3.12/site-packages/unidecode/__init__.py", line 60, in unidecode_expect_ascii
    bytestring = string.encode('ASCII')
                 ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by mgrfilipmarek** [comment]
- We can `return None` if there is an exception in `get_lunches(self, date):` method. But Im not sure if this is proper way to go as Im new in python and also cannot really reproduce. What do you think?

- Regarding unidecode error - I dont see a point why this happened as `unidecode` was not added or changed in this PR.

**Comment by rine77** [comment]
* at get_lunch problem should be handled in __init__.py by catching the error with try/except and only create lunch sensor if there is data
* the unicode error happens because the student_name is of Type None, this must be catched

**Comment by mgrfilipmarek** [comment]
Regarding "unidecode" issue - I guess its related to this bug #70 and should be solved separately. Would someone be able to overtake that pls?

**Comment by rine77** [comment]
I'd go for it but have 2 full range offsite working days and will not be back before friday.

**Review by rine77 — APPROVED** [review]
THANKS!
ready for christmas lunch release :)

**Pull request merged**
